### PR TITLE
Feature/glob option (second part)

### PR DESCRIPTION
**Pull request by TheElter**
Hi!
Sorry for the mess with the bad rebase :P

About the sample you mentioned in the other pull request, the fix is just in the commandline (index) so the mentioned test is actually correct (the "module" is working).

Want to add also the test on the commandline?

### CODE REVIEW

**Comment by allevo** [comment]
> Want to add also the test on the commandline?

It would be great!

**Comment by TheElter** [comment]
I cleaned some "wrong things" around and implemented the tests for commandline (all cases).

A question emerged:
the unused list should satisfy current flags or not?
The [actual implementation](https://github.com/allevo/packages-condom/blob/8807bf34c809c5affa6c980b4c53c7bbcfdbb0fe/condom.js#L168) implicitly assumes the defaults.

This lead to a funny output like this one:

    >$ node ./index.js test/data/example4/ --no-dependency
    Package foo is required at /Users/marco.biondi/repos/packages-condom/test/data/example4/index.js:3
    Package gearup is required at /Users/marco.biondi/repos/packages-condom/test/data/example4/index.js:4
    Package bar is required at /Users/marco.biondi/repos/packages-condom/test/data/example4/index.js:7
    Package wow is required at /Users/marco.biondi/repos/packages-condom/test/data/example4/index.js:8
    Unused package gearup
    Unused package foo

As you can see gearup and foo are considered like a Schrödinger's cat :)

**Comment by allevo** [comment]
> As you can see gearup and foo are considered like a Schrödinger's cat :)

That output is correct. The unused packages should be only a warning, not an error.
But for the time being this is not the behaviour. Can you fix it moving [this line](https://github.com/allevo/packages-condom/blob/master/output.js#L10) to [here](https://github.com/allevo/packages-condom/blob/master/output.js#L19)?

**Comment by TheElter** [comment]
> The unused packages should be only a warning, not an error.
If I understand the line you suggest is wrong: the status should be changed in type === 'miss' not in the else.
Please confirm so I do the last commit/push

**Comment by allevo** [comment]
> Please confirm so I do the last commit/push

Oki

**Comment by TheElter** [comment]
All done.

Bump version tag and publish on npm :P

**Pull request merged**
